# general settings
name: EDSR_Mx4_DIV2K_MTKD
model_type: MTKD
scale: 4
num_gpu: auto  # set num_gpu: 0 for cpu mode
manual_seed: 10

# dataset and data loader settings
datasets:
  train:
    name: DIV2K
    type: PairedImageDataset
    dataroot_gt: datasets/DIV2K800/GTmod12
    dataroot_lq: datasets/DIV2K800/LRbicx4
    filename_tmpl: '{}'
    io_backend:
      type: disk

    gt_size: 128
    use_hflip: true
    use_rot: true

    # data loader
    num_worker_per_gpu: 4
    batch_size_per_gpu: 16
    dataset_enlarge_ratio: 1
    prefetch_mode: ~

  val:
    name: Set5
    type: PairedImageDataset
    dataroot_gt: datasets/Set5/GTmod12
    dataroot_lq: datasets/Set5/LRbicx4
    io_backend:
      type: disk
# teacher network structures
tea1_network_g:
  type: SwinIR
  upscale: 4
  in_chans: 3
  img_size: 64
  window_size: 8
  img_range: 1.
  depths: [6, 6, 6, 6, 6, 6]
  embed_dim: 180
  num_heads: [6, 6, 6, 6, 6, 6]
  mlp_ratio: 2
  upsampler: 'pixelshuffle'
  resi_connection: '1conv'

# teacher path
tea1_path:
  pretrain_network_g: experiments/pretrained_models/001_classicalSR_DF2K_s64w8_SwinIR-M_x4.pth #001_classicalSR_DIV2K_s48w8_SwinIR-M_x2.pth
  strict_load_g: false
  resume_state: ~


# teacher network structures
tea2_network_g:
  type: EDSR
  num_in_ch: 3
  num_out_ch: 3
  num_feat: 256
  num_block: 32
  upscale: 4
  res_scale: 0.1
  img_range: 255.
  rgb_mean: [0.4488, 0.4371, 0.4040]

# path
tea2_path:
  pretrain_network_g: experiments/pretrained_models/EDSR_Lx4_f256b32_DIV2K_official-76ee1c8f.pth
  strict_load_g: false
  resume_state: ~


# teacher network structures
tea3_network_g:
    type: RCAN
    num_in_ch: 3
    num_out_ch: 3
    num_feat: 64
    num_group: 10
    num_block: 20
    squeeze_factor: 16
    upscale: 4
    res_scale: 1
    img_range: 255.
    rgb_mean: [ 0.4488, 0.4371, 0.4040 ]

# path
tea3_path:
  pretrain_network_g: ./experiments/ECCV2024model/MTKD2024/DCTSwinx4MTKDnet_g_25000.pth
  strict_load_g: false
  resume_state: ~


DCTSwin_network_g:
  type: DCTSwin
  upscale: 4
  in_chans: 9
  num_out_ch: 3
  img_size: 256
  window_size: 8
  img_range: 1.
  depths: [ 4, 4 ]
  embed_dim: 96  # mode num_heads size
  num_heads: [ 6, 6 ]
  mlp_ratio: 2
  upsampler: 'pixelshuffle'
  resi_connection: '1conv'

# path
DCTSwin_path:
  pretrain_network_g: experiments/DCTSwinx4/models/net_g_174000.pth
  strict_load_g: false
  resume_state: ~


# stu network structures
network_g:
  type: EDSR
  num_in_ch: 3
  num_out_ch: 3
  num_feat: 64
  num_block: 16
  upscale: 4
  res_scale: 1
  img_range: 255.
  rgb_mean: [0.4488, 0.4371, 0.4040]

# path
path:
  pretrain_network_g: experiments/ECCV2024model/MTKD2024/EDSRbl_MTKDx4_net_g_17000.pth #pretrained_models/EDSR_Mx2_f64b16_DIV2K_official-3ba7b086.pth
  strict_load_g: false
  resume_state: ~

# training settings
train:
  ema_decay: 0.999
  optim_g:
    type: Adam
    lr: !!float 2e-5
    weight_decay: 0
    betas: [0.9, 0.999]

  scheduler:
    type: MultiStepLR
    milestones: [200000, 400000, 600000]
    gamma: 0.5

  total_iter: 800000
  warmup_iter: -1  # no warm up

  # distill losses
  dis_opt:
    type: L1Loss
    loss_weight: 1
    reduction: mean

  # student losses
  stu_opt:
    type: L1Loss
    loss_weight: 0.1
    reduction: mean

  alpha: 0.1

# validation settings
val:
  val_freq: !!float 1e3
  save_img: false

  metrics:
    psnr: # metric name, can be arbitrary
      type: calculate_psnr
      crop_border: 2
      test_y_channel: true

# logging settings
logger:
  print_freq: 1000
  save_checkpoint_freq: !!float 1e3
  use_tb_logger: true
  wandb:
    project: ~
    resume_id: ~

# dist training settings
dist_params:
  backend: nccl
  port: 29500
